# Generated by Django 5.0.6 on 2024-07-20 06:28

import django.core.validators
import django.db.models.deletion
import movies.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Name')),
                ('country', models.CharField(max_length=2, verbose_name='Country')),
                ('dob', models.DateField(verbose_name='Date of birth')),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('production_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), movies.validators.YearValidator.max_year_validator], verbose_name='Production year')),
                ('actors', models.ManyToManyField(related_name='movies_actors', to='movies.artists', verbose_name='Actors')),
                ('director', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies_director', to='movies.artists', verbose_name='Director')),
            ],
        ),
    ]
