# Generated by Django 5.0.6 on 2024-07-22 03:26

import django.core.validators
from django.db import migrations, models

import movies.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='production_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(
                1888), movies.validators.YearValidator.max_year_validator], verbose_name='Production year'),
        ),
    ]
